# Generated by Django 5.0.6 on 2024-05-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_currentlocation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlocation',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='currentlocation',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
