# Generated by Django 5.0.6 on 2024-05-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_currentlocation_lat_currentlocation_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentlocation',
            old_name='state_code',
            new_name='pin_code',
        ),
    ]
