# Generated by Django 5.0.6 on 2024-05-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringrecord',
            name='criterion',
            field=models.CharField(choices=[('Temperature', 'Temperature'), ('Humidity', 'Humidity'), ('Pressure', 'Pressure')], max_length=20),
        ),
    ]
