# Generated by Django 5.0.6 on 2024-05-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_monitoringrecord_criterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
