# Generated by Django 5.0.6 on 2024-05-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weatherdata_lat_weatherdata_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='temperature',
            new_name='tem_min',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='temp_mas',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
