# Generated by Django 5.0.6 on 2024-05-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_rename_temperature_weatherdata_tem_min_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='tem_min',
            new_name='temp',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='temp_mas',
        ),
        migrations.AlterField(
            model_name='monitoringrecord',
            name='criterion',
            field=models.CharField(choices=[('temperature', 'temperature'), ('humidity', 'humidity'), ('pressure', 'pressure')], max_length=20),
        ),
    ]
