# Generated by Django 5.0.6 on 2024-05-15 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_rename_tem_min_weatherdata_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='weather.monitoringrecord'),
            preserve_default=False,
        ),
    ]
